#!/usr/bin/env pwsh
<#
.SYNOPSIS
  Scan interview-prep/ and java-toolkit/ to (re)generate:
    1. _sidebar.md     —— docsify left sidebar (also works as nav on GitHub Pages)
    2. README.md       —— update the "题目索引" block (between AUTO-INDEX markers)

.USAGE
  pwsh scripts/generate-index.ps1

.NOTES
  Run from the repo root (or anywhere — the script cd's to its own parent's parent).
  Idempotent: safe to run repeatedly. Re-run after adding/removing a note.
#>

$ErrorActionPreference = 'Stop'

# --- locate repo root --------------------------------------------------------
$repoRoot = Resolve-Path (Join-Path $PSScriptRoot '..')
Set-Location $repoRoot
Write-Host "Repo root: $repoRoot" -ForegroundColor Cyan

# --- categories --------------------------------------------------------------
$categories = [ordered]@{
    '01-array-hash'      = '数组 & 哈希'
    '02-sliding-window'  = '双指针 & 滑动窗口'
    '03-linked-list'     = '链表'
    '04-stack-queue'     = '栈 & 队列'
    '05-binary-search'   = '二分查找'
    '06-tree'            = '树'
    '07-graph'           = '图与搜索'
    '08-backtracking'    = '回溯'
    '09-dp'              = '动态规划'
    '10-heap'            = '堆 & 设计'
}

# --- helpers -----------------------------------------------------------------
function Get-ProblemMeta {
    param([string]$Path)
    $lines = Get-Content -LiteralPath $Path -TotalCount 6 -Encoding UTF8
    $title = $lines[0]
    # # [LeetCode 1. 两数之和 (Two Sum)](https://...)
    $m = [regex]::Match($title, '^#\s*\[?LeetCode\s+(\d+)\.\s*(.+?)\s*\(([^)]+)\)\]?')
    if (-not $m.Success) {
        # fallback: just strip markdown
        $clean = ($title -replace '^#\s*\[?', '' -replace '\]\(.*\)\s*$', '').Trim()
        return [pscustomobject]@{
            Number = 0; Zh = $clean; En = ''; Difficulty = ''; Tags = ''
        }
    }
    $num = [int]$m.Groups[1].Value
    $zh  = $m.Groups[2].Value.Trim()
    $en  = $m.Groups[3].Value.Trim()

    $difficulty = ''
    $tags = ''
    if ($lines.Count -ge 3) {
        $meta = $lines[2]
        # > 难度：Easy　|　标签：xxx, yyy　|　...
        $dm = [regex]::Match($meta, '难度[：:]\s*([A-Za-z\u4e00-\u9fff]+)')
        if ($dm.Success) { $difficulty = $dm.Groups[1].Value }
        $tm = [regex]::Match($meta, '标签[：:]\s*([^|｜]+)')
        if ($tm.Success) {
            $tags = ($tm.Groups[1].Value -replace '[\u3000\s]+$', '').Trim()
        }
    }

    [pscustomobject]@{
        Number     = $num
        Zh         = $zh
        En         = $en
        Difficulty = $difficulty
        Tags       = $tags
    }
}

# --- scan --------------------------------------------------------------------
$allProblems = New-Object System.Collections.Generic.List[object]
foreach ($cat in $categories.Keys) {
    $dir = Join-Path 'interview-prep' $cat
    if (-not (Test-Path $dir)) { continue }
    $files = Get-ChildItem -LiteralPath $dir -Filter 'leetcode-*.md' -File
    foreach ($f in $files) {
        $meta = Get-ProblemMeta -Path $f.FullName
        $rel  = ($f.FullName.Substring($repoRoot.Path.Length + 1)) -replace '\\', '/'
        $allProblems.Add([pscustomobject]@{
            Number     = $meta.Number
            Zh         = $meta.Zh
            En         = $meta.En
            Difficulty = $meta.Difficulty
            Tags       = $meta.Tags
            Category   = $cat
            CategoryZh = $categories[$cat]
            Path       = $rel
        })
    }
}

Write-Host "Found $($allProblems.Count) problem notes." -ForegroundColor Green

# --- build _sidebar.md -------------------------------------------------------
$sb = [System.Text.StringBuilder]::new()
[void]$sb.AppendLine('<!-- AUTO-GENERATED by scripts/generate-index.ps1 — do not edit manually -->')
[void]$sb.AppendLine()
[void]$sb.AppendLine('- [首页](/)')
[void]$sb.AppendLine()
[void]$sb.AppendLine('- [面试备考 · 题型分类](/interview-prep/README.md)')
foreach ($cat in $categories.Keys) {
    $catProblems = $allProblems | Where-Object Category -EQ $cat | Sort-Object Number
    if (-not $catProblems) { continue }
    $idx = ($cat -split '-')[0]
    [void]$sb.AppendLine("  - $idx · $($categories[$cat])")
    foreach ($p in $catProblems) {
        [void]$sb.AppendLine("    - [$($p.Number). $($p.Zh)](/$($p.Path))")
    }
}
[void]$sb.AppendLine()
[void]$sb.AppendLine('- [Java 工具箱](/java-toolkit/README.md)')
[void]$sb.AppendLine('  - [LeetCode IO 模板](/java-toolkit/java-leetcode-io-template/README.md)')
[void]$sb.AppendLine('  - [通用 IO 模板](/java-toolkit/java-io-template/README.md)')
[void]$sb.AppendLine('  - [集合速查](/java-toolkit/java-leetcode-collections/README.md)')
$collectionsDir = 'java-toolkit/java-leetcode-collections'
if (Test-Path $collectionsDir) {
    $colFiles = Get-ChildItem -LiteralPath $collectionsDir -Filter '*.md' -File |
        Where-Object Name -NE 'README.md' |
        Sort-Object Name
    foreach ($f in $colFiles) {
        $first = (Get-Content -LiteralPath $f.FullName -TotalCount 1 -Encoding UTF8) -replace '^#\s*', ''
        $rel = "/$collectionsDir/$($f.Name)"
        [void]$sb.AppendLine("    - [$first]($rel)")
    }
}

$sidebarPath = Join-Path $repoRoot '_sidebar.md'
$sb.ToString() | Set-Content -LiteralPath $sidebarPath -Encoding UTF8 -NoNewline
Write-Host "Wrote $sidebarPath" -ForegroundColor Green

# --- build README index block -----------------------------------------------
$idx = [System.Text.StringBuilder]::new()
[void]$idx.AppendLine('<!-- AUTO-INDEX:START — generated by scripts/generate-index.ps1 -->')
[void]$idx.AppendLine()
[void]$idx.AppendLine('### 按题号速查')
[void]$idx.AppendLine()
[void]$idx.AppendLine('| # | 题目 | 难度 | 分类 | 标签 | 笔记 |')
[void]$idx.AppendLine('|---|---|---|---|---|---|')
foreach ($p in ($allProblems | Sort-Object Number)) {
    $title = if ($p.En) { "$($p.Zh) ($($p.En))" } else { $p.Zh }
    [void]$idx.AppendLine("| $($p.Number) | $title | $($p.Difficulty) | $($p.CategoryZh) | $($p.Tags) | [笔记]($($p.Path)) |")
}
[void]$idx.AppendLine()
[void]$idx.AppendLine('### 按算法分类')
[void]$idx.AppendLine()
foreach ($cat in $categories.Keys) {
    $catProblems = $allProblems | Where-Object Category -EQ $cat | Sort-Object Number
    if (-not $catProblems) { continue }
    $idxNum = ($cat -split '-')[0]
    [void]$idx.AppendLine("#### $idxNum · $($categories[$cat])  _($($catProblems.Count) 题)_")
    [void]$idx.AppendLine()
    foreach ($p in $catProblems) {
        $diff = if ($p.Difficulty) { "_$($p.Difficulty)_ · " } else { '' }
        [void]$idx.AppendLine("- [$($p.Number). $($p.Zh)]($($p.Path)) $(if ($p.Difficulty -or $p.Tags) { '— ' + $diff + $p.Tags })")
    }
    [void]$idx.AppendLine()
}
[void]$idx.AppendLine('**统计**：共 ' + $allProblems.Count + ' 题（Easy ' +
    (($allProblems | Where-Object { $_.Difficulty -eq 'Easy' }).Count) + ' · Medium ' +
    (($allProblems | Where-Object { $_.Difficulty -eq 'Medium' }).Count) + ' · Hard ' +
    (($allProblems | Where-Object { $_.Difficulty -eq 'Hard' }).Count) + '）')
[void]$idx.AppendLine()
[void]$idx.AppendLine('<!-- AUTO-INDEX:END -->')

$readmePath = Join-Path $repoRoot 'README.md'
$readme = Get-Content -LiteralPath $readmePath -Raw -Encoding UTF8
$startTag = '<!-- AUTO-INDEX:START'
$endTag   = '<!-- AUTO-INDEX:END -->'
$startIdx = $readme.IndexOf($startTag)
$endIdx   = $readme.IndexOf($endTag)
if ($startIdx -ge 0 -and $endIdx -gt $startIdx) {
    $before = $readme.Substring(0, $startIdx)
    $after  = $readme.Substring($endIdx + $endTag.Length)
    $newReadme = $before + $idx.ToString().TrimEnd() + $after
    $newReadme | Set-Content -LiteralPath $readmePath -Encoding UTF8 -NoNewline
    Write-Host "Updated README.md (AUTO-INDEX block)" -ForegroundColor Green
} else {
    Write-Warning "README.md is missing the AUTO-INDEX markers. Add this where you want the index, then re-run:`n  <!-- AUTO-INDEX:START -->`n  <!-- AUTO-INDEX:END -->"
}

Write-Host "Done. Preview locally with:" -ForegroundColor Cyan
Write-Host "  npx docsify-cli serve ." -ForegroundColor Yellow
